// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/original": {
    params: {};
  };
  "/procedures/:procedureCode": {
    params: {
      "procedureCode": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/original" | "/procedures/:procedureCode";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/original.tsx": {
    id: "routes/original";
    page: "/original";
  };
  "routes/procedure-detail.tsx": {
    id: "routes/procedure-detail";
    page: "/procedures/:procedureCode";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/original": typeof import("./src/routes/original.tsx");
  "routes/procedure-detail": typeof import("./src/routes/procedure-detail.tsx");
};